name: Documentation

on:
  push:
    branches:
      - master

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout/@v4
    - uses: ammaraskar/sphinx-action@8.1.3
      with:
        docs-folder: docs/
    - uses: actions/upload-artifact@v4.4.3
      with:
        name: new-docs
        path: docs/_build/html/

  publish_pages:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs:
      - build_docs
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0

      - name: Download Docs Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: new-docs
          path: docs

      - name: Fix File Permissions for Pages
        run: chmod -R +rX docs

      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4.4.3
        with:
          separate-directories: true 

      - name: Download Merged Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: merged-artifacts
          path: merged-artifacts

      - name: Upload Merged Artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: merged-artifacts

      - name: Publish Docs to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
