name: Documentation

on:
  push:
    branches:
      - master

jobs:
  build_docs_old:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PtyPy Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          check-latest: true

      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: mpich

      - name: Install Sphinx
        run: pip install sphinx

      - name: Install PtyPy
        run: pip install .[full]

      - name: Prepare Tutorials
        working-directory: doc
        run: python script2rst.py

      - name: Prepare Templates
        working-directory: doc
        run: python tmp2rst.py

      - name: Prepare Parameters
        working-directory: doc
        run: python parameters2rst.py

      - name: Set Path to Sphinx Build
        run: echo "SPHINXBUILD=`which sphinx-build`" >> $GITHUB_ENV

      - name: Build Sphinx Documentation
        working-directory: doc
        run: make html

      - name: Upload Docs Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: old-docs
          path: doc/build/html/

  build_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PtyPy Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          check-latest: true

      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: mpich

      - name: Install Sphinx
        run: pip install sphinx myst_parser

      - name: Install PtyPy
        run: pip install .[full]

      - name: Install docs dependencies
        run: pip install -r docs/requirements.txt

      - name: Set Path to Sphinx Build
        run: echo "SPHINXBUILD=`which sphinx-build`" >> $GITHUB_ENV

      - name: Build Sphinx Documentation
        working-directory: docs
        run: make html
          
      - name: Upload Docs Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: new-docs
          path: docs/_build/html/

  publish_pages:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs:
      - build_docs_old
      - build_docs
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0

      - name: Download Old Docs Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: old-docs
          path: ./

      - name: Download Docs Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: new-docs
          path: ./docs

      - name: Fix File Permissions for Pages
        run: |
          chmod -R +rX .

      - name: Upload Merged Artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./

      - name: Publish Docs to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
