name: Documentation

on:
  push:
    branches:
      - master
      - dev

jobs:
  legacy_docs:
    uses: ./.github/workflows/_build_legacy_docs.yaml
    with: 
      tag: legacy

  new_docs:
    uses: ./.github/workflows/_build_docs.yaml
    with:
      tag: ${{ github.ref_name }}

  github_pages:
    needs:
      - legacy_docs
      - new_docs
    uses: ./.github/workflows/_github_pages.yaml
